### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AriellaJ** [kivy/kivy-designer#216] opened 2016-05-09 03:22 UTC
## Environment Info

kivy: 1.9.1
pygments: 2.1.3
docutils: 0.12
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.2
six: 1.10.0
kivy-garden: 0.1.4

Platform: Windows-7-6.1.7601-SP1
Python: 2.7.11

## Traceback

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python27\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python27\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Python27\Scripts\designer\nodetree.py", line 109, in _refresh
    self._clear_tree(self.tree, self.tree.root)
  File "C:\Python27\Scripts\designer\nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Python27\Scripts\designer\nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Python27\Scripts\designer\nodetree.py", line 102, in _clear_tree
    self._clear_tree(tree, n)
  File "C:\Python27\Scripts\designer\nodetree.py", lin

**Comment by aron-bordin** [comment] 2016-05-09 03:32
hi @AriellaJ 
Sorry, but the traceback is not complete. Are you able to reproduce this bug and post the full content ?

**Comment by aron-bordin** [comment] 2016-05-14 04:30
Hi,

I'm closing this bug report because the traceback is not complete. Please, read the Bug Reporter instruction, a complete report must end with "End of Traceback" in the last line. With this report we are not able to identify what is wrong here.

Thank you.

**Closed by aron-bordin** 2016-05-14 04:30 UTC
Labels: invalid
